name: BriefcaseMobileSigner

options:
  bundleIdPrefix: com.credentialbriefcase
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.4"
    CURRENT_PROJECT_VERSION: "1"

targets:
  BriefcaseMobileSigner:
    type: application
    platform: iOS
    sources:
      - path: BriefcaseMobileSigner
    info:
      path: BriefcaseMobileSigner/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.credentialbriefcase.mobile-signer
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
